version: '3.7'
services:
  notifications:
    build:
      context: ./notifications
  server:
    image: bidmcdigitalpsychiatry/lamp-server:2020
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      ROOT_KEY: '32_BIT_ENCRYPTION_KEY_HERE'
      CDB: 'http://admin:password@database:5984/'
      PUSH_API_GATEWAY: 'http://notifications:3000/push'
      PUSH_API_KEY: 'YOUR_PUSH_KEY_HERE'
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
  database:
    image: apache/couchdb:3.1.1
    healthcheck:
      test: curl --fail --silent http://localhost:5984/_up || exit 1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'password'
    volumes:
      - data-volume:/opt/couchdb/data
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
volumes:
  data-volume:
